CREATE TABLE student_financial_info (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255),
    assistance VARCHAR(255),
    religion VARCHAR(100),
    nrc VARCHAR(50),
    contact VARCHAR(50),
    school VARCHAR(255),
    course VARCHAR(255),
    program_duration INT,
    current_year INT,
    semester_term VARCHAR(50),
    total_course_cost DECIMAL(10, 2),
    estimated_fees_year_1 DECIMAL(10, 2),
    estimated_fees_year_2 DECIMAL(10, 2),
    estimated_fees_year_3 DECIMAL(10, 2),
    estimated_fees_year_4 DECIMAL(10, 2),
    estimated_fees_year_5 DECIMAL(10, 2),
    payment_date_sem1_year1 TIMESTAMP WITH TIME ZONE,
    payment_amount_sem1_year1 DECIMAL(10, 2),
    payment_date_sem1_year2 TIMESTAMP WITH TIME ZONE,
    payment_amount_sem1_year2 DECIMAL(10, 2),
    etc VARCHAR(255),
    other_fees_payment_date1 TIMESTAMP WITH TIME ZONE,
    other_fees_details1 VARCHAR(255),
    other_fees_amount1 DECIMAL(10, 2),
    other_fees_payment_date2 TIMESTAMP WITH TIME ZONE,
    other_fees_details2 VARCHAR(255),
    other_fees_amount2 DECIMAL(10, 2),
    other_fees_payment_date3 TIMESTAMP WITH TIME ZONE,
    other_fees_details3 VARCHAR(255),
    other_fees_amount3 DECIMAL(10, 2),
    projected_total_fees_current_year DECIMAL(10, 2),
    remaining_tuition_fees_current_year DECIMAL(10, 2),
    tuition_fees_paid_by VARCHAR(255),
    rent_payment_date1 TIMESTAMP WITH TIME ZONE,
    rent_paid_months1 VARCHAR(255),
    rent_amount1 DECIMAL(10, 2),
    rent_payment_date2 TIMESTAMP WITH TIME ZONE,
    rent_paid_months2 VARCHAR(255),
    rent_amount2 DECIMAL(10, 2),
    rent_payment_date3 TIMESTAMP WITH TIME ZONE,
    rent_paid_months3 VARCHAR(255),
    rent_amount3 DECIMAL(10, 2),
    rent_payment_date4 TIMESTAMP WITH TIME ZONE,
    rent_paid_months4 VARCHAR(255),
    rent_amount4 DECIMAL(10, 2),
    upkeep_payment_date1 TIMESTAMP WITH TIME ZONE,
    upkeep_paid_months1 VARCHAR(255),
    upkeep_amount1 DECIMAL(10, 2),
    upkeep_payment_date2 TIMESTAMP WITH TIME ZONE,
    upkeep_paid_months2 VARCHAR(255),
    upkeep_amount2 DECIMAL(10, 2),
    upkeep_payment_date3 TIMESTAMP WITH TIME ZONE,
    upkeep_paid_months3 VARCHAR(255),
    upkeep_amount3 DECIMAL(10, 2),
    upkeep_payment_date4 TIMESTAMP WITH TIME ZONE,
    upkeep_paid_months4 VARCHAR(255),
    upkeep_amount4 DECIMAL(10, 2)
);



CREATE TABLE temp_student_financial_info (
    id integer,
    name VARCHAR(255),
    assistance VARCHAR(255),
    religion VARCHAR(100),
    nrc VARCHAR(50),
    contact VARCHAR(50),
    school VARCHAR(255),
    course VARCHAR(255),
    program_duration INT,
    current_year INT,
    semester_term VARCHAR(50),
    total_course_cost DECIMAL(10, 2),
    estimated_fees_year_1 DECIMAL(10, 2),
    estimated_fees_year_2 DECIMAL(10, 2),
    estimated_fees_year_3 DECIMAL(10, 2),
    estimated_fees_year_4 DECIMAL(10, 2),
    estimated_fees_year_5 DECIMAL(10, 2),
    payment_date_sem1_year1 varchar(255),
    payment_amount_sem1_year1 DECIMAL(10, 2),
    payment_date_sem1_year2 varchar(255),
    payment_amount_sem1_year2 DECIMAL(10, 2),
    etc VARCHAR(255),
    other_fees_payment_date1 varchar(255),
    other_fees_details1 VARCHAR(255),
    other_fees_amount1 DECIMAL(10, 2),
    other_fees_payment_date2 varchar(255),
    other_fees_details2 VARCHAR(255),
    other_fees_amount2 DECIMAL(10, 2),
    other_fees_payment_date3 varchar(255),
    other_fees_details3 VARCHAR(255),
    other_fees_amount3 DECIMAL(10, 2),
    projected_total_fees_current_year DECIMAL(10, 2),
    remaining_tuition_fees_current_year DECIMAL(10, 2),
    tuition_fees_paid_by VARCHAR(255),
    rent_payment_date1 varchar(255),
    rent_paid_months1 VARCHAR(255),
    rent_amount1 DECIMAL(10, 2),
    rent_payment_date2 varchar(255),
    rent_paid_months2 VARCHAR(255),
    rent_amount2 DECIMAL(10, 2),
    rent_payment_date3 varchar(255),
    rent_paid_months3 VARCHAR(255),
    rent_amount3 DECIMAL(10, 2),
    rent_payment_date4 varchar(255),
    rent_paid_months4 VARCHAR(255),
    rent_amount4 DECIMAL(10, 2),
    upkeep_payment_date1 varchar(255),
    upkeep_paid_months1 VARCHAR(255),
    upkeep_amount1 DECIMAL(10, 2),
    upkeep_payment_date2 varchar(255),
    upkeep_paid_months2 VARCHAR(255),
    upkeep_amount2 DECIMAL(10, 2),
    upkeep_payment_date3 varchar(255),
    upkeep_paid_months3 VARCHAR(255),
    upkeep_amount3 DECIMAL(10, 2),
    upkeep_payment_date4 varchar(255),
    upkeep_paid_months4 VARCHAR(255),
    upkeep_amount4 DECIMAL(10, 2)
);