name: ikct ed

# Trigger on push to master branch
on:
  push:
    branches:
      - master

jobs:
  deploy_test_student_env:
    runs-on: self-hosted
    if: github.ref == 'refs/heads/master'
    environment: 
      name: prod env
      url: https://ikct.online/

    steps:

      - name: Set Permissions
        run: sudo chown -R $githubrunner:$githubrunner /root/work/ikct/test/ikct-ed

      - name: Deploy ikct for prod env
        run: |
          cd /root/work/ikct/test/ikct-ed
          git checkout master
          git pull origin master
          ./build_for_prod.sh
          sudo systemctl restart test.ikct.online.service
